
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:imgurdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: syncb
    password: 'syncb'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

imgur:
  base-url: https://api.imgur.com/3
  client-id: ${IMGUR_CLIENT_ID:}
  use-oauth2: false

security:
  jwt:
    secret: yourSuperSecretKeyThatShouldBeLongAndRandom1234567890
    expiration-minutes: 60
